name: dart001
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
#   path: ^1.8.0
  fpdart: ^0.6.0 # 1.0.0 doesnâ€™t support "plus" iterator

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.5
